// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $about from "./routes/about.tsx";
import * as $api_article from "./routes/api/article.tsx";
import * as $api_gallery_access from "./routes/api/gallery-access.ts";
import * as $api_group_submit from "./routes/api/group-submit.ts";
import * as $api_joke from "./routes/api/joke.ts";
import * as $api_mail from "./routes/api/mail.ts";
import * as $api_portfolio from "./routes/api/portfolio.tsx";
import * as $api_save_selection from "./routes/api/save-selection.ts";
import * as $articles from "./routes/articles.tsx";
import * as $articles_slug_ from "./routes/articles/[slug].tsx";
import * as $contact from "./routes/contact.tsx";
import * as $employee_slug_ from "./routes/employee/[slug].tsx";
import * as $gallery_slug_ from "./routes/gallery/[slug].tsx";
import * as $gallery_index from "./routes/gallery/index.tsx";
import * as $index from "./routes/index.tsx";
import * as $portfolio_comundo from "./routes/portfolio/comundo.tsx";
import * as $privacy_policy from "./routes/privacy-policy.tsx";
import * as $projects_slug_ from "./routes/projects/[slug].tsx";
import * as $robots_txt from "./routes/robots.txt.ts";
import * as $services from "./routes/services.tsx";
import * as $sitemap_xml from "./routes/sitemap.xml.tsx";
import * as $testemonials from "./routes/testemonials.tsx";
import * as $works from "./routes/works.tsx";
import * as $AboutUsSection_AboutUsSection from "./islands/AboutUsSection/AboutUsSection.tsx";
import * as $AnimatedAboutSection from "./islands/AnimatedAboutSection.tsx";
import * as $AnimatedCTASection from "./islands/AnimatedCTASection.tsx";
import * as $AnimatedContentSection from "./islands/AnimatedContentSection.tsx";
import * as $AnimatedImageSection from "./islands/AnimatedImageSection.tsx";
import * as $AnimatedServiceSection from "./islands/AnimatedServiceSection.tsx";
import * as $ArrowAnimation from "./islands/ArrowAnimation.tsx";
import * as $ArticlesIsland from "./islands/ArticlesIsland.tsx";
import * as $CategoryFilter from "./islands/CategoryFilter.tsx";
import * as $CleanHeroSection from "./islands/CleanHeroSection.tsx";
import * as $CollageParallax from "./islands/CollageParallax.tsx";
import * as $Forms_GalleryAccess from "./islands/Forms/GalleryAccess.tsx";
import * as $Forms_PromoForm from "./islands/Forms/PromoForm.tsx";
import * as $FullHeightServiceSection from "./islands/FullHeightServiceSection.tsx";
import * as $GalleryDisplay from "./islands/GalleryDisplay.tsx";
import * as $HeroSection1 from "./islands/HeroSection1.tsx";
import * as $LottieAnimation from "./islands/LottieAnimation.tsx";
import * as $MailerLite from "./islands/MailerLite.tsx";
import * as $Marquee_Marquee from "./islands/Marquee/Marquee.tsx";
import * as $MobileMenu_MobileMenu from "./islands/MobileMenu/MobileMenu.tsx";
import * as $ParallaxBackground from "./islands/ParallaxBackground.tsx";
import * as $PortfolioIsland from "./islands/PortfolioIsland.tsx";
import * as $PortfolioSection from "./islands/PortfolioSection.tsx";
import * as $ProgressBar_ProgressBar from "./islands/ProgressBar/ProgressBar.tsx";
import * as $ScrollText_ScrollText from "./islands/ScrollText/ScrollText.tsx";
import * as $ScrollTriggerImage from "./islands/ScrollTriggerImage.tsx";
import * as $ServiceCard_ServiceCard from "./islands/ServiceCard/ServiceCard.tsx";
import * as $ServiceSection_ServicesSection from "./islands/ServiceSection/ServicesSection.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
    "./routes/about.tsx": $about,
    "./routes/api/article.tsx": $api_article,
    "./routes/api/gallery-access.ts": $api_gallery_access,
    "./routes/api/group-submit.ts": $api_group_submit,
    "./routes/api/joke.ts": $api_joke,
    "./routes/api/mail.ts": $api_mail,
    "./routes/api/portfolio.tsx": $api_portfolio,
    "./routes/api/save-selection.ts": $api_save_selection,
    "./routes/articles.tsx": $articles,
    "./routes/articles/[slug].tsx": $articles_slug_,
    "./routes/contact.tsx": $contact,
    "./routes/employee/[slug].tsx": $employee_slug_,
    "./routes/gallery/[slug].tsx": $gallery_slug_,
    "./routes/gallery/index.tsx": $gallery_index,
    "./routes/index.tsx": $index,
    "./routes/portfolio/comundo.tsx": $portfolio_comundo,
    "./routes/privacy-policy.tsx": $privacy_policy,
    "./routes/projects/[slug].tsx": $projects_slug_,
    "./routes/robots.txt.ts": $robots_txt,
    "./routes/services.tsx": $services,
    "./routes/sitemap.xml.tsx": $sitemap_xml,
    "./routes/testemonials.tsx": $testemonials,
    "./routes/works.tsx": $works,
  },
  islands: {
    "./islands/AboutUsSection/AboutUsSection.tsx":
      $AboutUsSection_AboutUsSection,
    "./islands/AnimatedAboutSection.tsx": $AnimatedAboutSection,
    "./islands/AnimatedCTASection.tsx": $AnimatedCTASection,
    "./islands/AnimatedContentSection.tsx": $AnimatedContentSection,
    "./islands/AnimatedImageSection.tsx": $AnimatedImageSection,
    "./islands/AnimatedServiceSection.tsx": $AnimatedServiceSection,
    "./islands/ArrowAnimation.tsx": $ArrowAnimation,
    "./islands/ArticlesIsland.tsx": $ArticlesIsland,
    "./islands/CategoryFilter.tsx": $CategoryFilter,
    "./islands/CleanHeroSection.tsx": $CleanHeroSection,
    "./islands/CollageParallax.tsx": $CollageParallax,
    "./islands/Forms/GalleryAccess.tsx": $Forms_GalleryAccess,
    "./islands/Forms/PromoForm.tsx": $Forms_PromoForm,
    "./islands/FullHeightServiceSection.tsx": $FullHeightServiceSection,
    "./islands/GalleryDisplay.tsx": $GalleryDisplay,
    "./islands/HeroSection1.tsx": $HeroSection1,
    "./islands/LottieAnimation.tsx": $LottieAnimation,
    "./islands/MailerLite.tsx": $MailerLite,
    "./islands/Marquee/Marquee.tsx": $Marquee_Marquee,
    "./islands/MobileMenu/MobileMenu.tsx": $MobileMenu_MobileMenu,
    "./islands/ParallaxBackground.tsx": $ParallaxBackground,
    "./islands/PortfolioIsland.tsx": $PortfolioIsland,
    "./islands/PortfolioSection.tsx": $PortfolioSection,
    "./islands/ProgressBar/ProgressBar.tsx": $ProgressBar_ProgressBar,
    "./islands/ScrollText/ScrollText.tsx": $ScrollText_ScrollText,
    "./islands/ScrollTriggerImage.tsx": $ScrollTriggerImage,
    "./islands/ServiceCard/ServiceCard.tsx": $ServiceCard_ServiceCard,
    "./islands/ServiceSection/ServicesSection.tsx":
      $ServiceSection_ServicesSection,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
